added support for proxy_protocol
AntagonistHQ/puppet-nginx pull request #1
Opened 2022-12-08 15:13 UTC by jtlamers

2022-12-08 15:16 UTC, tjikkun commented
Ik zou hem rebasen naar upstream master

2022-12-09 15:19 UTC, tjikkun requested changes

2022-12-09 15:19 UTC, tjikkun commented on manifests/resource/mailhost.pp
> +  if is_string($listen_port) {
This should not be added I think

2022-12-09 15:19 UTC, tjikkun commented on spec/defines/resource_mailhost_spec.rb
> +<<<<<<< HEAD
This should not be here

2022-12-09 15:19 UTC, tjikkun commented on spec/defines/resource_mailhost_spec.rb
> +
extra newline should not be here

2022-12-09 15:19 UTC, tjikkun commented on templates/mailhost/mailhost.erb
> -
Why did you remove this?

2022-12-12 09:23 UTC, jtlamers commented on manifests/resource/mailhost.pp
> +  if is_string($listen_port) {
aangepast

2022-12-12 09:23 UTC, jtlamers commented on spec/defines/resource_mailhost_spec.rb
> +<<<<<<< HEAD
adjusted

2022-12-12 09:23 UTC, jtlamers commented on spec/defines/resource_mailhost_spec.rb
> +
removed newline

2022-12-12 09:23 UTC, jtlamers commented on templates/mailhost/mailhost.erb
> -
readded newline

2022-12-12 10:30 UTC, tjikkun approved these changes

2022-12-12 13:03 UTC, merged